blank_issues_enabled: true
contact_links:
  - name: Bitcoin Core Security Policy
    url: https://github.com/Fixed-Blockchain/fixedcoin/blob/master/SECURITY.md
    about: View security policy
  - name: Bitcoin Core Developers
    url: https://fixedcoin.org
    about: Bitcoin Core homepage
